### ISSUE TITLE
[jsonConfig]:  invalid jsonConfig for iconPosition

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#266]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

IDE

### Warning message

```
shelly has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"iconPosition"},"message":"must NOT have additional properties"}]
--


### Source link

https://github.com/iobroker-community-adapters/ioBroker.shelly/blob/da263b4b74140681438307fc3d8ae47927d4bb61/admin/jsonConfig.json#L4

https://github.com/klein0r/ioBroker.octoprint/blob/12f9b463dc62b1d537cc4d10be7f8203282395d6/admin/jsonConfig.json#L4



### Additional information

Related https://github.com/ioBroker/adapter-react-v5/issues/197 which did not fix the issue obviously.

**Comment by foxriver76** [comment]
fixed by https://github.com/ioBroker/adapter-react-v5/commit/0a492c6ead64e28677e3e5e3197b4329a5f33de1

**Comment by mickym2** [comment]
This is not fixed as with the node red Adapter the error still exists

**Comment by mcm1957** [comment]
> This is not fixed as with the node red Adapter the error still exists

Cannot be reproduced.  
Node-red still display a jsonConfig error - but NOT this one. So its Ok for this issue to be closed.

@mickym2:
Please mnot that invalidJson conig Warning is not one error but depends on the concrete text logged.
Please

**Comment by mickym2** [comment]
Ok - so fine for me. I do not understand why in my original post this issue was linked. (https://github.com/ioBroker/ioBroker.node-red/issues/458#issuecomment-2007936474) 

I am also not sure how your new opened issue is related to my originial issue (https://github.com/ioBroker/ioBroker.node-red/issues/458#issue-2195581439)  - but I am fine if someone cares about this issue. 

I think it is difficult for endusers to differentiate the warning for invalid jsonConfigs of the NodeRed adapter with different contents.

**Comment by klein0r** [comment]
> I think it is difficult for endusers to differentiate the warning for invalid jsonConfigs

I agree - that was the reason for this issue: https://github.com/ioBroker/ioBroker.admin/issues/2421
